name: verify-java

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    verify-java:
        runs-on: ubuntu-latest
        steps:
            # This step uses the `actions/checkout` action to download a copy of your repository on the runner.
            -   uses: actions/checkout@v3
            # This step uses the `actions/setup-java` action to configure the Eclipse Temurin (Java) 17 JDK by
            # Eclipse Adoptium.
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
            # The "Build with Maven" step runs the Maven `verify` target in non-interactive mode to ensure that your
            # code builds, tests pass, and a package can be created.
            # The -f option indicates the root of the Maven project, where the pom.xml is located
            -   name: Build Multipart Payload examples with Maven
                run: mvn -f 'Java/Endpoint Examples/Multipart Payload' --show-version --batch-mode --update-snapshots verify
            -   name: Build JSON Payload examples with Maven
                run: mvn -f 'Java/Endpoint Examples/JSON Payload' --show-version --batch-mode --update-snapshots verify
            -   name: Build Complex Flow examples with Maven
                run: mvn -f 'Java/Complex Flow Examples' --show-version --batch-mode --update-snapshots verify
